name: filebeat

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /app/log/*logfile.log
  fields:
    log_type: system

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false


processors:
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["10.11.0.19:5044"]
  username: filebeat_internal
  password: ${FILEBEAT_INTERNAL_PASSWORD}

http:
  enabled: true
  host: 0.0.0.0
